plugins {
    id 'dev.scaffoldit' version '0.2.+'
}

version = project.mod_version

hytale {
    usePatchline 'release'
    useVersion project.hytale_version

    repositories {
        mavenCentral()
    }

    dependencies {
    }

    manifest {
        group = project.group
        name = project.name
        main = project.entry_point
        version = project.version
        serverVersion = project.hytale_version
        disabledByDefault = false
        includesAssetPack = false
        dependencies = [
                'Hytale:EntityModule': '*',
                'Hytale:ItemModule': '*'
        ]
        subPlugins = []
    }
}
